### PR TITLE
motion methods should use ShortName()

### PR DESCRIPTION
**Pull request by biotinker**

### CODE REVIEW

**Comment by edaniels** [comment]
shouldn't we update other parts to accept a full name? short name is riskier

**Comment by biotinker** [comment]
@edaniels Isn't that functionally what this is doing? Counterintuitively, `Name` yields just the name of the thing, while `ShortName` yields remote+name, which is how it is in the framesystem (that counterintuitiveness is the cause of this bug).

The only information that's not captured in ShortName is the subtype, but we shouldn't care about that for framesystem stuff, since ShortName should always be unique in a robot.

**Comment by edaniels** [comment]
there's the .String() which is the fully qualified name with all remotes involved

**Comment by biotinker** [comment]
.String() is subtype/remote:component, whereas ShortName is just remote:component.

Remote:component is what the framesystem uses, so that's what should be used here.

If we want the framesystem to use subtype/remote:component I'm not opposed to that but that should be coordinated with the RDK Components team, and also we probably shouldn't block this PR on that; this will fix the system as it currently exists, and that would be an improvement that re-updating this would be a part of.

**Review by Fahmina — APPROVED** [review]
LGTM

**Review by bhaney — APPROVED** [review]
Yay short name

**Comment by edaniels** [comment]
ah, yes. my bad!

**Comment by biotinker** [comment]
Whoops. Git did a merge commit rather than a rebase; not sure why. Sorry about that.

**Pull request merged**
