### PR TITLE
RSDK-8570 Utilize `StoppableWorkers` from goutils

### PR DESCRIPTION
**Pull request by benjirewis**
## Hardware testing

Tested with canary rovers to ensure
- Sessions stopped correctly
- MoveStraight terminated at expected times
- SetPower could start and stop motors
- A generic linux board could represent a pi5 and build correctly 
- No errors occurred during shutdown and no goroutines were leaked

### CODE REVIEW

**Comment by randhid** [comment]
Do you want to wait until @penguinland comes back from vacation? Also for bucket prs - you should add what was tested and verified on hardware in the pr comment.

benji the bucketeer.

**Comment by benjirewis** [comment]
> you should add what was tested and verified on hardware in the pr comment.

Did my best to describe in PR description.

> benji the bucketeer.

🪣 ❤️ 

> Do you want to wait until @penguinland comes back from vacation?

Probably wise, I'll request him. Only exception might be if NetCode needs to get a goutils fix in before then (we shouldn't have to).

**Review by randhid — APPROVED** [review]
Approving in case a goutils bump is necessary, but @penguinland will be back from vacation on Tuesday

**Review by penguinland — APPROVED** [review]
LGTM! Thanks for taking the initiative while I was on vacation.

**Pull request merged**
