### PR TITLE
[RSDK-6277] Remove board packages

### PR DESCRIPTION
**Pull request by randhid**
Removing the board package from the cli command. Let me know if there are other places you added them that I couldn't see immediately.

### CODE REVIEW

**Review by oliviamiller — APPROVED** [review]
lgtm, there were also changes made in [app](https://github.com/viamrobotics/app/pull/2309/files) that will need to be removed too.

**Comment by randhid** [comment]
@zaporter-work there is no harm in removing this right now? Are there any steps to update viam cli or will that be done upon the next release?

**Review by zaporter-work — APPROVED** [review]
@randhid Yup! This all looks good.

The cli will be updated with the next rdk release.

**Comment by randhid** [comment]
> @randhid Yup! This all looks good.
> 
> The cli will be updated with the next rdk release.

I have another PR for app https://github.com/viamrobotics/app/pull/3606, do I need to merge them soon after each other? Or should I wait for rdk to release then merge that one in? Or is it all okay since I haven't changed the API yet?

**Comment by zaporter-work** [comment]
> I have another PR for app https://github.com/viamrobotics/app/pull/3606, do I need to merge them soon after each other?

You will break users of this API / cli commands no matter how this is done. However, if there are no users, I don't think there are any timing constraints and you should be free to merge as desired.

**Comment by zaporter-work** [comment]
App PR is looking good too. Will want to do a migration to remove all of the existing packages, but that could be done as a followup PR.

**Pull request merged**
