### PR TITLE
RSDK-5832 - Add static FFmpeg libraries for Mac

### PR DESCRIPTION
**Pull request by seanavery**
## Description

This PR simply adds static libraries for Darwin(arm64). The `make ffmpeg` command worked well! Adjusted CGO build constraints for FFMPEG golang wrappers to hit for Darwin builds. I am assuming that we will not worry about Darwin(x86).

## Testing
- Build `make server` works on Mac and no regressions for canon builds.
- Webcam working on MacOS and no regression on Linux/aarch64.
- Testing here that CI passes....
- I have not been able to verify by inspecting the binary that libraries have been added. Using `nm bin/Darwin-arm64/viam-server | grep avutil` does not return anything, but perhaps the symbols are being stripped?
- avcodec unit test passes.

### CODE REVIEW

**Comment by bazile-clyde** [comment]
>     * I have not been able to verify by inspecting the binary that libraries have been added. Using `nm bin/Darwin-arm64/viam-server | grep avutil` does not return anything, but perhaps the symbols are being stripped?

I think so. That would make sense given that the size doesn't really increase when we add these static libs. The easiest way to test would be to run `go test -v -run TestEncoderIsAvailable ./gostream/ffmpeg/avcodec`.

**Comment by bazile-clyde** [comment]
Also, we'll need to update `entrypoint_unix/linux.go` files. I _think_ `entrypoint_unix.go` at this point can be used only for `android && no_cgo` and may need a name change. I'd test and double-check with Abe though.

**Comment by seanavery** [comment]
> > ```
> > * I have not been able to verify by inspecting the binary that libraries have been added. Using `nm bin/Darwin-arm64/viam-server | grep avutil` does not return anything, but perhaps the symbols are being stripped?
> > ```
> 
> I think so. That would make sense given that the size doesn't really increase when we add these static libs. The easiest way to test would be to run `go test -v -run TestEncoderIsAvailable ./gostream/ffmpeg/avcodec`.

The avcodec unit test passes.

**Comment by seanavery** [comment]
@abe-winter Trying to figure out what changes need to be made to the entrypoint. Seems fine to leave `entrypoint_unix.go` build constraints the same but just wanting to make sure.

**Comment by seanavery** [comment]
> Also, we'll need to update `entrypoint_unix/linux.go` files. I _think_ `entrypoint_unix.go` at this point can be used only for `android && no_cgo` and may need a name change. I'd test and double-check with Abe though.

@bazile-clyde Are you talking about specifically excluding darwin in `entrypoint_linux.go`? I am thinknig entry point changes should only become relevant when we move away from gostream codecs to use avcodec here.

**Review by abe-winter — APPROVED** [review]

**Comment by abe-winter** [comment]
re entrypoints -- _linux and _unix versions are identical except for build constraints + a comment

but I have no problems with leaving as-is if the build is working

**Comment by seanavery** [comment]
> re entrypoints -- _linux and _unix versions are identical except for build constraints + a comment
> 
> but I have no problems with leaving as-is if the build is working

@bazile-clyde  Are you  ok with current PR? We can modify entrypoints when we change out StreamConfig codecs.

**Comment by bazile-clyde** [comment]
> > re entrypoints -- _linux and _unix versions are identical except for build constraints + a comment
> > but I have no problems with leaving as-is if the build is working
> 
> @bazile-clyde Are you ok with current PR? We can modify entrypoints when we change out StreamConfig codecs.

That makes sense to me.

**Review by bazile-clyde — APPROVED** [review]
LGTM! Thanks for knocking this out so quickly!

**Pull request merged**
