### PR TITLE
[RSDK-5486] - Add stop header button to navigation card

### PR DESCRIPTION
**Pull request by micheal-parks**

### CODE REVIEW

**Review by DTCurrie — APPROVED** [review]
✅

**Review by EshaMaharishi — APPROVED** [review]
Looks great!

Discussed offline that maybe in the near future we can refactor the design to make it clearer - e.g. rename the "Manual" toggle to "Off", or have a "Start" button

**Review by mcous — APPROVED** [review]
Are there tests we should be adding for this functionality?

**Comment by micheal-parks** [comment]
> Are there tests we should be adding for this functionality?

@mcous Will address in a follow up. I'll have to set up Vitest in RC first.

**Pull request merged**
