### PR TITLE
RSDK-6233: Remove attribute map converter from extrinsic camera model

### PR DESCRIPTION
**Pull request by hexbabe**
https://viam.atlassian.net/browse/RSDK-6233

Before merging I will try to test with real robot

### CODE REVIEW

**Comment by cheukt** [comment]
will take a look after testing

**Review by bazile-clyde — APPROVED** [review]
LGTM. I verified this still works as expected and is reconfigured properly.

**Review by bazile-clyde — CHANGES_REQUESTED** [review]
As we discussed, I also see the `Constructor` is called repeatedly in this PR but not in the `main` branch. The actual stream appears to be working fine, though.

**Comment by cheukt** [comment]
the config struct may need to be updated to resemble the json attrs more closely, so that the conversion can take place without causing issues.

**Comment by hexbabe** [comment]
> As we discussed, I also see the `Constructor` is called repeatedly in this PR but not in the `main` branch. The actual stream appears to be working fine, though.

> the config struct may need to be updated to resemble the json attrs more closely, so that the conversion can take place without causing issues. (the code should also be able to access conf.ConvertedAttributes instead of conf.Attributes)

The fix I wrote for this is to use the generic NativeConfig converter to convert the config, and extracted the part of the config that was diff-ing (IntrinsicExtrinsic) into a separate state. This way the diffs don't trigger and the structs match

**Comment by hexbabe** [comment]
Sorry for not surfacing this in my original PR description— I thought it was out of scope for this ticket and was gonna write a bug ticket later. Good that we can fix it here though. Still not 100% sure that this won't break the actual camera, so @bazile-clyde when you get the time, could you test it on your extrinsic cam again. TYSM

**Review by bazile-clyde — APPROVED** [review]
LGTM. Verified that this resource no longer repeatedly calls its constructor.

**Review by cheukt — APPROVED** [review]
LGTM

**Pull request merged**
