### PR TITLE
RSDK-2960 - Fix order of execution for 2D slam ui when first loaded or refreshed

### PR DESCRIPTION
**Pull request by nfranczak**
just removing un-needed code.

slamui

### CODE REVIEW

**Comment by nicksanford** [comment]
> just removing un-needed code.
> 
> slamui

Can you please manually test that refreshing the map using manual refresh & the interval also renders as expected?

**Review by nicksanford — APPROVED** [review]

**Review by micheal-parks — APPROVED** [review]

**Comment by nfranczak** [comment]
> Can you please manually test that refreshing the map using manual refresh & the interval also renders as expected?

@nicksanford I gotchu. will do right now and upload a new screen recording

**Comment by nfranczak** [comment]
slamui

**Review by jeremyrhyde — APPROVED** [review]
LGTM

**Pull request merged**
