### PR TITLE
RSDK-1646 Configure cors to allow all origins

### PR DESCRIPTION
**Pull request by maximpertsov**
JIRA: https://viam.atlassian.net/browse/RSDK-1646

### CODE REVIEW

**Review by edaniels — APPROVED** [review]
LGTM but @AdamMagaluk what do you think about this? Fine for now? I imagine we "may" want to have it configurable in the future.

**Review by Kschappacher — APPROVED** [review]
LGTM

**Comment by AdamMagaluk** [comment]
Yeah I agree with Eric, we also might want to call that out in docs or elsewhere.

LGTM.

**Review by AdamMagaluk — APPROVED** [review]

**Comment by edaniels** [comment]
cc: @mcvella to document state of CORS of viam-server being all wildcarded

**Pull request merged**
