### PR TITLE
Move static source to fake

### PR DESCRIPTION
**Pull request by randhid**
this was just being used in transformpipeline's tests. so I moved it there.

### CODE REVIEW

**Comment by randhid** [comment]
Alright I learned some thigns from this endeavour:
- Some tests in `transformpipeline' are hidden behind a `c_go` and/or a `!tflite` build flag, some because they use a tflite object for tests, some because of potentially removed things in `rimage`
- This would pull in a package because it was dependent on whatever packages `StaticSource` was in.
- `image_file` cameras are built under a `!no_cgo` flag. If `StaticSource` was moved out of the go package that `image_file`'s registration was currently in, it would skip the init that registers that resource in the `buildRobotWithDetector` and `buildRobotWithClassifier`  calls in the `transformpipeline`'s tests.
- This didn't affect `viam-server` because `go build` does not include the test files.

I'm basically blocked by the tflite being in the rdk, or I figure out the build flag circus which I do not want to do.

Now the question is:
1) given it's marginally less code tidiness right now - do we like this change? Happy to scale down this commit to just the fly by code-cleanup changes (removing useages of the cursed `gihtub.com/pkg/errors` and the one `Projector` I found hiding in the client struct doing nothing.
2) This makes me want to carve camera out of the Videosource struct even more. We should have a brainstorming session about that.

**Comment by hexbabe** [comment]
> potentially removed things

libjpeg?

**Comment by hexbabe** [comment]
> * This would pull in a package because it was dependent on whatever packages `StaticSource` was in.
> * `image_file` cameras are built under a `!no_cgo` flag. If `StaticSource` was moved out of the go package that `image_file`'s registration was currently in, it would skip the init that registers that resource in the `buildRobotWithDetector` and `buildRobotWithClassifier` calls in the `transformpipeline`'s tests.

So what exactly is the test build violation? I see that all tests actually passed except motion-specific ones

**Comment by randhid** [comment]
> > * This would pull in a package because it was dependent on whatever packages `StaticSource` was in.
> > * `image_file` cameras are built under a `!no_cgo` flag. If `StaticSource` was moved out of the go package that `image_file`'s registration was currently in, it would skip the init that registers that resource in the `buildRobotWithDetector` and `buildRobotWithClassifier` calls in the `transformpipeline`'s tests.
> 
> So what exactly is the test build violation? I see that all tests actually passed except motion-specific ones

The motion test is a red herring that has nothing to do with what I was observing. I think their workflow is broken and will be notifying them soon.

What was happening was that `TestClassifierSource` and similar tests in `transformpipeline` using a `buildRobotWithX` helper. That method included a robot config passed in with an `image_file` camera model. When `StaticSource` was not part of the same package that initialised and registered  the `image_file`, it wasn't building it as part of the robot used in tests because of the build flags that determined was was complied for testing when running `go test`.

**Comment by randhid** [comment]
> > > * This would pull in a package because it was dependent on whatever packages `StaticSource` was in.
> > > * `image_file` cameras are built under a `!no_cgo` flag. If `StaticSource` was moved out of the go package that `image_file`'s registration was currently in, it would skip the init that registers that resource in the `buildRobotWithDetector` and `buildRobotWithClassifier` calls in the `transformpipeline`'s tests.
> > 
> > 
> > So what exactly is the test build violation? I see that all tests actually passed except motion-specific ones
> 
> The motion test is a red herring that has nothing to do with what I was observing. I think their workflow is broken and will be notifying them soon.
> 
> What was happening was that `TestClassifierSource` and similar tests in `transformpipeline` using a `buildRobotWithX` helper. That method included a robot config passed in with an `image_file` camera model. When `StaticSource` was not part of the same package that initialised and registered the `image_file`, it wasn't building it as part of the robot used in tests because of the build flags that determined was was complied for testing when running `go test`.
> 
> The error I was getting was "error resource not registered 'builtin:camera:image_file'" as an output error from the `camera.FromRobot` call in `TestClassifier` and the three other tests in `transformpipeline` that pull in `tflite` build dependencies.

This may need a diagram to explain.

**Comment by jckras** [comment]
Qs for my own understanding - Why are we replacing "videosource" with "fake" camera (other than that the title says Move static source to fake)? Does the "!no_cgo" flag mean a cgo package is enabled? What is the rimage package used for?

**Comment by randhid** [comment]
> Qs for my own understanding - 
>Why are we replacing "videosource" with "fake" camera (other than that the title says Move static source to fake)? 
I moved the package where the logic for the "image_file" camera, and had to move the `StaticSource` object with it for a build reason. When you change which go package that code is in, other parts of the codebase that were importing `StaticSource` from `videosource` now must import them from `fake`  

>Does the "!no_cgo" flag mean a cgo package is enabled? What is the rimage package used for?
It means that parts of the code using this logic has a [cgo](https://pkg.go.dev/cmd/cgo) dependency, and the binary being built  is built with that [build tag](https://www.digitalocean.com/community/tutorials/customizing-go-binaries-with-build-tags). These built tags mostly protect our android build of viam-server, which can't import most of the heavy cgo libraries like tensorflow-lite "tflite".

 rimage is a package used mostly by vision to do fancy computer vision things like segmenting 2d and 3d images and projecting 3d images from 2d images. We sometimes have to deal with it in go since some cameras output pointclouds from 2d images, like the "webcam" and the "image_file" models.

**Review by jckras — APPROVED** [review]
LGTM

**Review by hexbabe — APPROVED** [review]
I think even though we wanted to do more, the current state of the PR is still an improvement.

**Pull request merged**
