### PR TITLE
Remove mistakenly passing package replacement test

### PR DESCRIPTION
**Pull request by zaporter-work**
Was reading through some robot tests when I stumbled upon this test (I must've missed it). 

Everything that this test is supposed to test is already tested elsewhere. Unfortunately, this test also passes when it should clearly fail (the placeholders are invalid and are never evaluated).

I don't see the value in fixing this test given that the things it tests are tested elsewhere and because it was already broken.

If you feel strongly that it should be replaced, happy to look into putting something in its place.

### CODE REVIEW

**Comment by RoxyFarhad** [comment]
can you point to where the tests are happening?

**Comment by zaporter-work** [comment]
`config/placeholder_replacement_test.go`

**Comment by zaporter-work** [comment]
As per actually starting the ml service, those happen in `services/vision/mlvision/ml_model_test.go`

**Review by RoxyFarhad — APPROVED** [review]
lgtm!

**Pull request merged**
