### PR TITLE
RSDK-5459 - Correct starting configuration for plannerSetupFromMoveRequest in CheckPlan

### PR DESCRIPTION
**Pull request by nfranczak**

### CODE REVIEW

**Comment by tessavitabile** [comment]
@nfranczak I think @biotinker or @raybjork should review instead of me

**Review by biotinker — CHANGES_REQUESTED** [review]
I'm pretty sure this is not what we want. What's the motivation here?

**Review by jeremyrhyde — CHANGES_REQUESTED** [review]
rejected <3

**Comment by nfranczak** [comment]
closing this until it is picked back up

**Pull request closed without merging**
