### PR TITLE
RSDK-7952 - Remove join_color_depth camera model

### PR DESCRIPTION
**Pull request by seanavery**
Simple PR to remove `join_color_depth` model from the RDK. We now have `get_point_cloud` support native to the `viam-camera-realsense` module.

### CODE REVIEW

**Review by randhid — APPROVED** [review]
Be sure to have the migration script written and ready to run next Tuesday before you merge this.

**Comment by hexbabe** [comment]
> Be sure to have the migration script written and ready to run next Tuesday before you merge this.

Would the migration script just be deleting the model? Nothing to replace with

**Review by hexbabe — COMMENTED** [review]
Are there any spatial math helper functions we should remove as well?

**Comment by seanavery** [comment]
@hexbabe mentioned that a migration script to move users over does not make sense since this functionality is now in the realsense mod which this camera model is commonly paired with. But I guess that would make sense to run a delete script.

**Comment by randhid** [comment]
> Are there any spatial math helper functions we should remove as well?

Yes a script to delete this from configs is necessary, since otherwise vima-server will error with a "resource not registered or found" when the model is deleted, breaking users' online robots.

**Comment by randhid** [comment]
> > Be sure to have the migration script written and ready to run next Tuesday before you merge this.
> 
> Would the migration script just be deleting the model? Nothing to replace with

Yes, same as what we did for the other models we completely removed.

**Comment by hexbabe** [comment]
Got it. @seanavery I can show you the script for that tomorrow

**Comment by seanavery** [comment]
> Are there any spatial math helper functions we should remove as well?

- `RGBDToPointCloud` ❌  used in vision/segmentation and other areas.
- `rimage.ConvertImageToDepthMap` ❌  used in camera.go and transform camera pipelines.
- `RGBDToPointCloud` ❌  commonly used.
- `SimultaneousColorDepthNext` ✅ Looks like we can safely remove this helper.
- `NewPinholeModelWithBrownConradyDistortion` ❌  used in webcam and others.

Good call, I was able to remove one 🎉

**Comment by seanavery** [comment]
@randhid @hexbabe The migration script looks good to go -- planning on merging this.

**Pull request merged**
