### PR TITLE
remove timeout on ntrip client

### PR DESCRIPTION
**Pull request by JohnN193**
pr updates the ntrip client to remove the timeout that is set by default. this results in the ntrip client not having to reconnect every 15 seconds due to the GetStream http request getting canceled from the timeout. See Timeout from the [http Client documentation](https://pkg.go.dev/net/http#Client)

### CODE REVIEW

**Comment by susmitaSanyal** [comment]
We should test this against all the CORS server that we have access to so far before merging. Other server may kick us out for being connected too long

**Review by penguinland — APPROVED** [review]
John also pointed out to me that [reading successfully-returned data after the timeout also results in an error](https://cs.opensource.google/go/go/+/refs/tags/go1.22.5:src/net/http/client.go;l=93-94): even if we get data quickly, if we take too long to read it, the timeout can interfere anyway.

I'm still surprised that gognss (creator of the ntrip library we're using) set the default timeout to 15 seconds. I wonder why he didn't set it to 0 like this.

What happens if the wifi goes down, and we can't contact the caster at all? Will we attempt to connect forever without ever indicating that we might have some kind of failure? (What do we currently do in that situation? I wonder if that's already the case, and this PR doesn't change any user-visible behavior.)

IIRC these components can already take a long time to shut down if they're in the middle of some web request. If we set the timeout to 0 and then try to close the component while it's in the middle of a request, might we need to wait arbitrarily long for it to finish closing?

Assuming there are good answers to those questions, LGTM!

**Comment by penguinland** [comment]
> Other server may kick us out for being connected too long

If you mean they close our connection eventually, that's totally fine: ReceiveAndWrite will reconnect when that happens. If you mean the organization might suspend our login credentials, I'd be very surprised, but if that's a possibility we should indeed check on it.

**Comment by JohnN193** [comment]
> John also pointed out to me that [reading successfully-returned data after the timeout also results in an error](https://cs.opensource.google/go/go/+/refs/tags/go1.22.5:src/net/http/client.go;l=93-94): even if we get data quickly, if we take too long to read it, the timeout can interfere anyway.
> 
> I'm still surprised that gognss (creator of the ntrip library we're using) set the default timeout to 15 seconds. I wonder why he didn't set it to 0 like this.
> 
> What happens if the wifi goes down, and we can't contact the caster at all? Will we attempt to connect forever without ever indicating that we might have some kind of failure? (What do we currently do in that situation? I wonder if that's already the case, and this PR doesn't change any user-visible behavior.)
> 
> IIRC these components can already take a long time to shut down if they're in the middle of some web request. If we set the timeout to 0 and then try to close the component while it's in the middle of a request, might we need to wait arbitrarily long for it to finish closing?
> 
> Assuming there are good answers to those questions, LGTM!

I think theres still a misunderstanding here, after connecting to the caster we only make [one http request](https://github.com/viamrobotics/rdk/blob/5234b47d49169a2d5911f896033e8e94d8b78a26/components/movementsensor/gpsrtkserial/gpsrtkserial.go#L244), which[ returns the stream](https://github.com/de-bkg/gognss/blob/684a4285a1da1797a7b54eed46d3ae176251a362/pkg/ntrip/client.go#L240-L311) to the corrections. We then take that resp.Body and pass that into the [teeReader](https://github.com/viamrobotics/rdk/blob/5234b47d49169a2d5911f896033e8e94d8b78a26/components/movementsensor/gpsrtkserial/gpsrtkserial.go#L382) to give to the gps. 

it does not randomly take 15 seconds to get a piece of correction data sometimes. before we were explicitly creating the http request to say "only get data for 15 seconds"

**Comment by JohnN193** [comment]
> We should test this against all the CORS server that we have access to so far before merging. Other server may kick us out for being connected too long

sounds good, can bother ya tomorrow to learn how to set that up

**Comment by JohnN193** [comment]
After doing some testing, I realized our VRS implementation does not even use this chunk of code after grabbing the initial source table. This means we only use the ntrip client for
1. reading the source table
2. receiving rctm corrections when not using VRS. 

its possible we want to have different timeouts for reading from the source table(normally it takes at most 3-5 seconds, but a failure will block for 30 seconds when no timeout is configured) and receiving corrections(ideally we shouldn't disconnect)

Adding the comment and then merging

**Pull request merged**
