### PR TITLE
APP-1979: update bump and release workflows to unblock RC hotfixes

### PR DESCRIPTION
**Pull request by mcous**
## Overview

This PR updates CI workflows to unblock `@viamrobotics/rc` hotfix releases. The difference between the mainline RDK release process (Gitflow-style) and the RC release process (CD from `main`) make hotfixes for RC difficult to unblock cleanly. In my opinion, a larger overhaul of the release process - and/or removing the RC package from this repository - should be considered.

There is more than one way to approach this problem. This PR represents an approach @stevebriskin and I discussed yesterday that minimizes changes to existing workflows and processes. I'm very happy to change this around if folks are tolerant of larger changes.

## Change log

- Update "Bump remote-control Version" workflow (`npm-bump-version.yml`)
   - Open PR against the requested branch rather than `main`, so that bumps can target the release branch for hotfixes
   - Allow TypeScript SDK dependency update to be skipped, and **make skipping the TS SDK update the default behavior**
   - Allow any bump level to RC (e.g. `patch`, `minor`, arbitrary version)
- Update  "Build and Publish Stable" (`stable.yml`) to publish NPM versions, if needed
- Update  "Build and Publish RC" (`releasecandidate.yml`) to publish NPM versions, if needed

### Test procedure

1. Merge this branch into `main` on my fork
2. Trigger the "Bump remote control version" workflow in my fork
    - [x] Verify PR can target arbitrary branch
    - [x] Verify RC bump will be patch if unspecified
    - [x] Verify RC bump can be specified
    - [x] Verify TS SDK will be skipped if unspecified
    - [x] Verify TS SDK bump can be specified

I have not tested the addition of `npm_publish` to the tag-based workflows, because they are more straightforward than the bump workflow changes and well tested in their own right.

## Proposed RC hotfix process

The proposed RC hotfix would, by the necessity of the branching and existing CI setup, require an RDK hotfix. This process would work regardless of whether the RDK actually needed changes cherrypicked.

0. Cherry-pick RDK changes into release branch, if required (regular RDK hotfix process)
1. Run the "Bump remote-control Version" workflow against the release branch
4. A PR will be opened into the release branch, review and merge it to bump RC version for the hotfix
5. Verify tests pass by manually running the "test" workflow on the release branch (regular RDK hotfix process)
6. Publish a new tag for the RDK (regular RDK hotfix process)
    - This will release the RDK hotfix _and_ the RC hotfix
7. **After CI has released everything** Run "Bump remote-control Version" workflow again, this time against `main`, to ensure versions are synced between the release branch and `main`
    - Since version has already been published, the merge into `main` will not trigger another release

### Potential additional changes

Additional changes we could make, in ascending amount of effort / process change:

- Allow "Pull Request Update" (`pullrequest-trusted.yml`) to run against PRs into `v0.xyz-release` branches, so that step (3) above isn't needed
- Add a new workflow that runs on pushes to `v0.xyz-release` to run npm publish, so that step (4) above isn't needed
- Add a new part of the process to sync the release branch back into `main` after a release, so that step (5) above isn't required
    - This starts getting us closer to canonical [Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) with separate `main`, `develop`, release, and hotfix branches
    - Gitflow may be a good fit for this repository / release process, given that we're not currently practicing CD
    - Gitflow comes with its own pain points, but so does this sort-of-CD-sort-of-giflow process that we've currently got going on

### CODE REVIEW

**Review by Otterverse — APPROVED** [review]
LGTM

I'm fine with however those more directly involved want the release workflows to go. I only made this bump one in the first place to automate otherwise manual steps for tenzing. It wasn't really considered in the greater context of human workflow/process (aka "gitflow") or anything.

**Review by stevebriskin — APPROVED** [review]
LGTM. Curious to see how testing works out.
I think the changes in stable.yml should also be added to releasecandidate.yml.

**Review by tessavitabile — APPROVED** [review]
LGTM. Thank you for doing this!

Can you please work with Tenzing to update https://viam.atlassian.net/wiki/spaces/PROCESS/pages/263487493/Release+process+step+by+step+guide?

**Comment by mcous** [comment]
I made one change in response to testing on my fork: I changed the name of the RC bump branch from `workflow/bump-remote-control` to `workflow/bump-remote-control/${{ branch }}`.

- Regular release: branch will be `workflow/bump-remote-control/main`
- Hotfix release: branch will be `workflow/bump-remote-control/release_v...`

This ensure the bump process for a hotfix will not interfere with any ongoing mainline bump process if those two bumps need to run in parallel for some reason

**Comment by mcous** [comment]
Reviewed process changes with @10zingpd and updated the release docs. Will merge this PR once CI is green post-main-sync

**Pull request merged**
