### PR TITLE
DATA-2728

### PR DESCRIPTION
**Pull request by nicksanford**
[Ticket](https://viam.atlassian.net/browse/DATA-2728)

This removes the code that will uplaod .prog files which have not been updated in the past 10 seconds.

### CODE REVIEW

**Review by vijayvuyyuru — COMMENTED** [review]
The change itself looks good to me. I wanted to talk about what we would want to do with .prog files now since its possible they are just permanently on disk after this goes out. Is that behaviour we're ok with?

**Comment by nicksanford** [comment]
> The change itself looks good to me. I wanted to talk about what we would want to do with .prog files now since its possible they are just permanently on disk after this goes out. Is that behaviour we're ok with?

The behavior we want is For when viam-server first boots, data-management to convert all .prog files into .capture files if they are valid protobuf and if not to move them to the failed directory. 

I'm not sure how long it will take me to get a working PR for that behavior so I figured that while we are in this triage period, we would prefer to lose one or two files worth of data rather than risk blocking the data collectors from collecting data at all.

**Review by agreenb — COMMENTED** [review]
You mentioned in your Excalidraw plan that data capture can detect .prog files exist from a previous viam-server, converts it to a .capture file, and will only sync .capture files — which is great.

There's also the scenario where the data capture rate is low enough vs the sync rate, so it'd delay sync until the files are large enough to be converted into .capture files. I'd want to test this with a setup that mimics a customer's in order to measure how much it'd delay syncing new data — which is what they care most about getting asap.

**Comment by vijayvuyyuru** [comment]
> There's also the scenario where the data capture rate is low enough vs the sync rate, so it'd delay sync until the files are large enough to be converted into .capture files. I'd want to test this with a setup that mimics a customer's in order to measure how much it'd delay syncing new data — which is what they care most about getting asap.

If I'm understanding correctly, wouldn't this case be handled if online by calling `svc.flushCollectors()` as that would immediately convert a .prog to capture file which would be synced asap instead of having to wait for it to get larger?

**Review by agreenb — APPROVED** [review]
Yep you're correct @vijayvuyyuru, good call to you and @nicksanford! LGTM

**Review by vijayvuyyuru — APPROVED** [review]
Agreed, LGTM!

**Review by dmhilly — APPROVED** [review]
LGTM, thanks everyone for the questions on the PR, it made this change much easier to follow.

**Pull request merged**
