### PR TITLE
RSDK-7512: arm and gripper geometries always returns unimplemented error

### PR DESCRIPTION
**Pull request by martha-johnston**
not sure if there's a reason these were different, but arm and gripper were always returning unimplemented error when calling `Geometries` from the sdk, but this fixed it

### CODE REVIEW

**Comment by martha-johnston** [comment]
@raybjork want to make sure this won't mess up any arm stuff

**Review by JohnN193 — APPROVED** [review]
looks like base has had a [similar pr](https://github.com/viamrobotics/rdk/pull/2566) in the past to implement this fix. 

LGTM

**Comment by raybjork** [comment]
There probably should have been a unit test catching this failure, similar to the one that was added to the base PR. Could you add one to this PR? Otherwise LGTM

**Review by raybjork — APPROVED** [review]
Thanks for adding the tests!

**Pull request merged**
