### PR TITLE
check OS + architecture of binary in `validateModuleFile`

### PR DESCRIPTION
**Pull request by abe-winter**
## What changed
- when validating a tarball, make sure the binary matches the desired platform (e.g. linux/arm64 vs linux/amd64). Warn if not
## Why
We've seen people upload binaries of the wrong architecture when first doing cross-platform work; this makes that situation slightly louder, to save debugging time
## Notes
- I made it a warning rather than an error because I'm not sure how complete / correct the parser is. It's designed to fail silently unless the system is reasonably sure something is wrong.
- This is silent if someone is using a run.sh
- This is silent for 32-bit arm
## Screenshot
(The yellow warning line is new).
Screenshot from 2024-08-07 16-50-38

### CODE REVIEW

**Comment by abe-winter** [comment]
actually hold off review -- `file` command takes a file on stdin, I'm taking out the CreateTemp stuff

**Comment by abe-winter** [comment]
ready

**Review by zaporter-work — APPROVED** [review]
Did a manual test -- Works for me on linux/amd64.

Nice! This is a big win. I had assumed this was impossible because we would have to support `run.sh` files & would need to execute the program. Using `file` is a good idea.

Also works well for `linux/any` `any/amd64`, and `any` modules because any `run.sh` files won't be checked but any non-platform agnostic binaries emit this warning. (had to think about this one for a bit. There are ~70 modules in prod using `any` as a platform. Want to make sure we don't break them)

**Comment by abe-winter** [comment]
thanks for testing `any` + looking at live modules

yeah my rough design approach to `any` was that a platform-specific binary is wrong for `any`; so either:
1. there is a multi-platform thing in run.sh, in which case we can't parse `file` output and we skip checking
2. the user has a platform-specific binary which will fail on some platforms and the warning is correct

**Review by michaellee1019 — APPROVED** [review]
LGTM! Nice update. I tested by running `file` in my macos terminal with some pyinstaller built binaries I see it returning the correct info so I like this approach.

**Comment by abe-winter** [comment]
thank you for mac test!!

**Pull request merged**
