### PR TITLE
RSDK-5835: Remove libvpx dependency

### PR DESCRIPTION
**Pull request by jckras**
I deleted the vpx folder from rdk/gostream/codec and then built the rdk on darwin/arm64, linux/arm64, and linux/amd64 without it.

I tested the livestream on darwin/arm64 (mac) with a Webcam camera component.
I tested livestream on linux/arm64(raspberry pi) with a Webcam camera component.
I tested livestream on linux/amd64(framework) with Webcam camera component.

### CODE REVIEW

**Comment by jckras** [comment]
darwin/arm64 (mac):
darwin:arm64 (mac)

**Comment by jckras** [comment]
linux/arm64(raspberry pi), testing the live stream works on webcam camera:
linux:arm64 (pi4b)

**Comment by jckras** [comment]
linux/amd64(framework), testing the live stream works on webcam camera:
linux:amd64 - framework

**Review by randhid — APPROVED** [review]
LGTM!

**Review by hexbabe — CHANGES_REQUESTED** [review]
I noticed apt install `libvpx-dev` and brew install `libvpx` are still in our `setup.sh` script. They were [added by Clyde when we brought gostream in](https://github.com/hexbabe/sean-rdk/commit/62a90bf97859d77343c49be628acfd02d1a30758). Let's remove those too since they look to be deps solely for this gostream encoder we're removing.

**Comment by hexbabe** [comment]
Also referenced in https://github.com/viamrobotics/rdk/blob/main/gostream/shell.nix

**Review by randhid — CHANGES_REQUESTED** [review]
You now have a bad commit tree, there are many ways to solve it, did you rebase on main?

**Comment by jckras** [comment]
I removed `apt install libvpx-dev` and `brew install libvpx` from the setup.sh script and removed `pkgs.libvpx` from shell.nix. I learned that setup.sh is not used in production so I only tested on macOS but it ran successfully.

**Review by randhid — APPROVED** [review]

**Review by hexbabe — APPROVED** [review]
Nice! LGTM

**Pull request merged**
