### PR TITLE
NetAppender.Close early exit

### PR DESCRIPTION
**Pull request by abe-winter**
## What changed
- add exit-if-no-progress feature to `NetAppender.Close`
- internal `NetAppender.close()` method which can take mocks
## Why
When the device is offline, we were waiting like 20 seconds to shut down viam-agent. (10 for viam-server + 10 for agent).

Follow-up to https://github.com/viamrobotics/rdk/pull/4128#issuecomment-2189531398
## Test runs
The new warning (from `go test -v`) looks like this:
> net_appender.go:160: 2024-06-28T15:56:46.928-0400	WARN		logging/net_appender.go:160	NetAppender.Close() did not progress in 100ms, closing with 1 still in queue

### CODE REVIEW

**Review by cheukt — APPROVED** [review]

**Comment by abe-winter** [comment]
converting this one to draft -- in real-life test, the background process still hung for 10 seconds

```
2024-06-28T20:31:07.185Z	INFO	robot_server	impl/resource_manager.go:434	Now removing resource	{"resource":"rdk-internal:service:frame_system/builtin"}
2024-06-28T20:31:08.733Z	WARN	netlogger	logging/net_appender.go:159	NetAppender.Close() did not progress in 1.5s, closing with 13 still in queue
2024-06-28T20:31:12.190Z	INFO	netlogger	logging/net_appender.go:282	error logging to network: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2024-06-28T20:31:17.190Z	INFO	netlogger	logging/net_appender.go:282	error logging to network: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

**Comment by abe-winter** [comment]
I changed the shutdown logic so that:
- NetAppender.backgroundWorker doesn't sync again after a cancel
- remoteWriter.write inherits the parent NetAppender's cancel context

the cancel happens at the end of the retry loop in NetAppender.Close, so we don't need to do more attempts afterwards

my manual test case for this is to boot rdk with network, disable wifi on my laptop, and then ctrl-C. seems to close cleanly:
```
2024-06-28T22:09:04.732Z	INFO	robot_server	impl/resource_manager.go:434	Now removing resource	{"resource":"rdk-internal:service:frame_system/builtin"}
2024-06-28T22:09:06.283Z	WARN	netlogger	logging/net_appender.go:159	NetAppender.Close() did not progress in 1.5s, closing with 12 still in queue
2024-06-28T22:09:06.283Z	INFO	netlogger	logging/net_appender.go:281	error logging to network: rpc error: code = Canceled desc = context canceled
```

**Comment by cheukt** [comment]
> remoteWriter.write inherits the parent NetAppender's cancel context
can we not let the try complete and then cancel? just worried that maybe the last call may be in progress and we kill it prematurely

**Comment by abe-winter** [comment]
> worried that maybe the last call may be in progress and we kill it prematurely

cancelBackgroundWorkers gets called at the bottom of NetAppender.close, after the sleep loop

I brought in the cancel context because we have in theory already waited the time we wanted to wait, and without the parent context, remoteLogWriterGRPC.write waits up to 5 seconds on top of that

(can revert if you think this is wrong)

**Comment by cheukt** [comment]
I think the code as it is will only try once if the first call doesn't connect - maybe we can lower the timeout in remoteLogWriterGRPC.write so that we try at least twice?

**Review by cheukt — APPROVED** [review]
lgtm!

**Pull request merged**
