### PR TITLE
RSDK-8824: Test Datarace: go.viam.com/rdk/components/base/sensorcontrolled.TestSensorBaseWithVelocitiesSensor

### PR DESCRIPTION
**Pull request by martha-johnston**
after further investigation the issue was in the `Next()` function of various blocks. I added a lock to each, but I'm wondering if this will cause issues. @JohnN193 do you remember why we haven't done this yet? I did a quick test with tuning and behavior of controlled components with these changes and didn't see any issues

### CODE REVIEW

**Comment by JohnN193** [comment]
I don't think there was a particular reason, I tried to ask why we didn't have locks in the past and never got a response back. Chose not to add locks because we had a ticket to fix the controls/motor tests so figured all the other blocks could happen then.

**Review by JohnN193 — APPROVED** [review]
LGTM, but could you check the behavior of the skipped tests in sensorcontrolled_test.go and controlled motor?

**Comment by martha-johnston** [comment]
> LGTM, but could you check the behavior of the skipped tests in sensorcontrolled_test.go and controlled motor?

they all still fail

**Comment by martha-johnston** [comment]
going to run more extensive hardware tests tomorrow to make sure this doesn't break anything.

**Pull request merged**
