### PR TITLE
RSDK-4279 hang in test start waypoint calling set mode cancels current and future move on globe calls

### PR DESCRIPTION
**Pull request by biotinker**
Tracked down both race conditions and fixed them

### CODE REVIEW

**Review by Otterverse — APPROVED** [review]
LGTM for what this does fix. Though I'm not convinced it fixes all the races seen. I definitely saw logged lines coming from cBiRTT.go and I believe there are still problems in that file.

**Comment by Otterverse** [comment]
FYI, this is one such case I _think_ I see over in the other file. https://github.com/viamrobotics/rdk/blob/main/motionplan/cBiRRT.go#L126C46-L135 Basically if context is cancelled, it returns immediately, even though the background routine may still be running (and attempting to return data, depending where it was when cancellation happened.)

**Comment by biotinker** [comment]
@Otterverse The changes here ought to address the specific flaky test from the ticket because it was the `planManager` returning early while CBiRRT was still running that caused that flakiness. In practice `plan()` should never be called on CBiRRT as it should be able to jump straight to `rrtBackgroundRunner`

But you are correct that the line you linked is a landmine just waiting for the same issue to happen; I will correct it there as well.

**Comment by Otterverse** [comment]
> But you are correct that the line you linked is a landmine just waiting for the same issue to happen; I will correct it there as well.

Thanks! Looks good!

**Pull request merged**
