### PR TITLE
RSDK-7328: Change DigitalIntrruptByName to return a  DigitalInterrupt and an error

### PR DESCRIPTION
**Pull request by martha-johnston**
accidentally closed my other pr

### CODE REVIEW

**Comment by martha-johnston** [comment]
tried to merge main in a weird way and accidentally closed my old PR. This is the same just updated with main

**Review by randhid — APPROVED** [review]
LGTM!

**Comment by randhid** [comment]
> okay now actually running everything on the right branch and these tests are still passing locally on a pi. any suggestions on how to repo?

What are you running on the pi? make test or make test-pi?

**Comment by martha-johnston** [comment]
> What are you running on the pi? make test or make test-pi?

`go test -run TestPiPigpio`

**Comment by martha-johnston** [comment]
still never got it to fail on my pi but I did figure out why it was failing so

**Pull request merged**
