### PR TITLE
Delete ffmpeg

### PR DESCRIPTION
**Pull request by randhid**
Confirmed: stream works with webcam, audio input works with fake.
Screenshot 2024-08-05 at 20 26 13

Builds in linux:
```
Removing ffmpeg (7:5.1.4-0+deb12u1) ...
testbot@691d5e223cd1:/host$ go run web/cmd/server/main.go -config removeffmpeg.json 
go: downloading go.viam.com/api v0.1.330
2024-08-05T23:40:01.519Z	INFO	rdk	config/logging_level.go:38	Log level initialized: info
2024-08-05T23:40:01.519Z	INFO	rdk	server/entrypoint.go:97	Viam RDK built from source; version unknown
2024-08-05T23:40:01.929Z	WARN	rdk	config/reader.go:337	No cached config, using cloud TLS config.
2024-08-05T23:40:02.264Z	INFO	rdk	impl/local_robot.go:1253	(Re)configuring robot
2024-08-05T23:40:02.265Z	INFO	rdk.resource_manager	impl/resource_manager.go:636	Now configuring resource	{"resource":"rdk:service:sensors/builtin"}
2024-08-05T23:40:02.267Z	INFO	rdk.resource_manager	impl/resource_manager.go:636	Now configuring resource	{"resource":"rdk:component:camera/camera-1"}
2024-08-05T23:40:02.268Z	INFO	rdk.resource_manager	impl/resource_manager.go:636	Now configuring resource	{"resource":"rdk:service:motion/builtin"}
```

TODO:

- [x] Confirm raspberry pi webcam is unharmed
- [x] Decide if we also remove the ffmpeg camera, it will now need ffmpeg to be installed outside of rdk. UPDATE: ffmpeg needs to be installed separately from rdk anyway on linux systems. On mac, our brew dependencies ensure that ffmpeg is installed on the system.

Tasks now that I have a gameplan:
- [x] Test on x86 Linux with Webcam.  No FFMPEG or libjpeg-turbo present in the build environment
- [x] Test on Raspberry Pi with webcam. No FFMPEG or libjpeg-turbo present in the build environment
- [x] Test on Mac with Webcam.  No FFMPEG or libjpeg-turbo present in the build environment
- [x]  Test that the `image_file` viam component on x86 shows up and has feature parity. 
- [x] Test that the `image_file` viam component shows up on Mac and has feature parity. 
- [x] Test that `image_file` viam component on arm64 shows up and has feature parity. 
- [ ]  Test that the `audio_input:fake` viam component on x86 shows up and has feature parity. 
- [x] Test that the `audio_input:fake` viam component shows up on Mac and has feature parity. 
- [x] Test that `audio_input:fake` viam component on arm64 shows up and has feature parity.

### CODE REVIEW

**Comment by randhid** [comment]
Tests on Mac. Fake AudioInput made a sound:
Screenshot 2024-08-28 at 18 29 02
Screenshot 2024-08-28 at 18 29 10
Screenshot 2024-08-28 at 18 29 23
Screenshot 2024-08-28 at 18 30 08

**Comment by randhid** [comment]
Tests on arm64 Raspberry pi - had to use sudo to run viam-server
Note: testing one remote at a time because of crappy multiple header requests sent bug in the front end. That's why the others aren't live.

Audio input makes noise.

Screenshot 2024-08-28 at 18 57 50
Screenshot 2024-08-28 at 18 57 56
Screenshot 2024-08-28 at 18 58 06
Screenshot 2024-08-28 at 18 58 27

**Comment by randhid** [comment]
And x86 is crashing when I add an audioinput component It does not on main. Going to investigate further.

**Comment by randhid** [comment]
Tests on x86 Linux
Screenshot 2024-08-28 at 19 25 00
Screenshot 2024-08-28 at 19 25 05
Screenshot 2024-08-28 at 19 25 15

**Comment by randhid** [comment]
@hexbabe @seanavery @abe-winter I think I'm ready.

**Comment by hexbabe** [comment]
I have a few questions. I think I get the point of this PR: to remove FFMPEG as a static dep

1. What were we even using it for? 
2. Are we expecting users to have it installed now if we haven't migrated the functionality off to another lib?

**Comment by randhid** [comment]
> I have a few questions. I think I get the point of this PR: to remove FFMPEG as a static dep
> 
>     1. What were we even using it for?
I have no clue.

>     2. Are we expecting users to have it installed now if we haven't migrated the functionality off to another lib?
We already do for the ffmpeg camera on linux, I tested with a raspberry pi running viam-server with an ffmpeg camera and it just starts yelling with:
Screenshot 2024-08-29 at 15 37 06

We have a darwin /etc/setup brew installation instruction for FFmpeg, but that is for developers to setup their dev environment with. So I assume that viam-server running on a mac in the wild would do the same thing. I can double check that now on my machine by yeetign my ffmpeg install if you'd like.

**Review by abe-winter — APPROVED** [review]
seems fine to me from dependencies perspective, guessing camera crew will have better situational awareness though

**Comment by randhid** [comment]
I looked into it since we distribute our mac servers over brew, we install the ffmpeg dependencies for mac in brew as well. These files were not helping run the ffmpeg model on mac.

**Review by hexbabe — APPROVED** [review]

**Comment by randhid** [comment]
Checked with an `rtsp` camera and a `fake` camera with rtp passthrough set to true
Screenshot 2024-08-29 at 16 49 34
Screenshot 2024-08-29 at 16 50 39

**Comment by randhid** [comment]
Okay. YOLO

**Pull request merged**
