### PR TITLE
[RSDK-7630] update board status in frontend

### PR DESCRIPTION
**Pull request by JohnN193**
Updates to match this api: https://github.com/viamrobotics/api/pull/490

ticket: https://viam.atlassian.net/browse/RSDK-7630

### CODE REVIEW

**Review by ethanlook — COMMENTED** [review]
Code LGTM, have you tested this with a real board?

It's worth noting that this breaking change means RC will not work for old RDK versions from before the API change now.

**Comment by JohnN193** [comment]
Good point, we were just testing with fake yesterday. Can make sure this gets tested with a board

> It's worth noting that this breaking change means RC will not work for old RDK versions from before the API change now.

Should be fine, we mainly noticed it because the new API wasn’t functioning when people were testing

**Comment by randhid** [comment]
> Good point, we were just testing with fake yesterday. Can make sure this gets tested with a board
> 
> > It's worth noting that this breaking change means RC will not work for old RDK versions from before the API change now.
> 
> Should be fine, we mainly noticed it because the new API wasn’t functioning when people were testing

We should hold off on this change until micro-rdk is also updated, cc @npmenard

**Comment by randhid** [comment]
> > Good point, we were just testing with fake yesterday. Can make sure this gets tested with a board
> > > It's worth noting that this breaking change means RC will not work for old RDK versions from before the API change now.
> > 
> > 
> > Should be fine, we mainly noticed it because the new API wasn’t functioning when people were testing
> 
> We should hold off on this change until micro-rdk is also updated, cc @npmenard

The pr we're waiting for: https://github.com/viamrobotics/micro-rdk/pull/207

**Comment by JohnN193** [comment]
Do we still want to get this into the release

**Comment by randhid** [comment]
> Do we still want to get this into the release

We need to wait until micro-rdk merges their PR in, I believe, since the board is functional, and it may affect a project in fight. Can you check with @npmenard or @stevebriskin to see if anything has changed there?

**Comment by npmenard** [comment]
> > Do we still want to get this into the release
> 
> We need to wait until micro-rdk merges their PR in, I believe, since the board is functional, and it may affect a project in fight. Can you check with @npmenard or @stevebriskin to see if anything has changed there?

@Gautham should confirm but i think micro-rdk is covered

**Comment by randhid** [comment]
> > > Do we still want to get this into the release
> > 
> > 
> > We need to wait until micro-rdk merges their PR in, I believe, since the board is functional, and it may affect a project in fight. Can you check with @npmenard or @stevebriskin to see if anything has changed there?
> 
> @Gautham should confirm but i think micro-rdk is covered

Okay we'll wait for @gvaradarajan to confirm. The pr on micro-rdk isn't merged in yet https://github.com/viamrobotics/micro-rdk/pull/207

**Review by ethanlook — APPROVED** [review]

**Pull request merged**
