### PR TITLE
RSDK-5528: Remove mmal from rdk/gostream

### PR DESCRIPTION
**Pull request by jckras**
I deleted the mmal package from rdk/gostream/codec and then built the rdk on darwin/arm64, linux/arm64, and linux/amd64 without it.

- I tested the livestream on darwin/arm64 (mac) with a Webcam camera component. 
- I tested livestream on linux/arm64(raspberry pi) with a Fake camera component.
- I tested livestream on linux/amd64(framework) with Webcam camera component.

### CODE REVIEW

**Comment by jckras** [comment]
darwin/arm64 (mac):
darwin:arm64-mac

**Comment by jckras** [comment]
linux/arm64(raspberry pi) - With the raspberry pi I only tested with the fake camera. I reviewed the logs to see that there were no error messages when viewing in "live" mode but I am not sure if the fake camera is a sufficient test?
linux:arm64 (raspberry pi)

**Comment by jckras** [comment]
linux/amd64(framework):
x86-amd64-linux

**Review by randhid — CHANGES_REQUESTED** [review]
Let's test with a webcam on the raspberry pi. I can show you where to get a camera in the robotics lab.

**Comment by jckras** [comment]
Updated test on linux/arm64(raspberry pi) using a webcam - No error messages and video worked when livestream was on. 
Screenshot 2024-08-30 at 11 48 48 AM

**Review by randhid — APPROVED** [review]
LGTM!

**Review by seanavery — APPROVED** [review]
LGTM. Thanks for thoroughly testing live-stream across all of the platforms 🎉

**Pull request merged**
