### PR TITLE
fix enable pin bug when turning off gpio motor

### PR DESCRIPTION
**Pull request by gvaradarajan**
Bug was introduced in this commit: https://github.com/viamrobotics/rdk/commit/85163fd8a8b452269531054926e4407838aa6964

### CODE REVIEW

**Review by randhid — APPROVED** [review]
tested?

**Comment by gvaradarajan** [comment]
> tested?

not yet, trying to secure some hardware

**Comment by randhid** [comment]
> > tested?
> 
> not yet, trying to secure some hardware

let's try to wrap this up so you don't have to context switch anymore!

**Comment by randhid** [comment]
> > > tested?
> > 
> > 
> > not yet, trying to secure some hardware
> 
> let's try to wrap this up so you don't have to context switch anymore!

ie I'm okay with merging this now.

**Comment by gvaradarajan** [comment]
tested on hardware, merging

**Pull request merged**
