### PR TITLE
bump package.json + packge-lock.json

### PR DESCRIPTION
**Pull request by nfranczak**
bump due to: https://github.com/viamrobotics/viam-typescript-sdk/pull/249

### CODE REVIEW

**Review by ethanlook — COMMENTED** [review]
Is `0.10.2-next.0` after `0.11.0-rc.0`?

**Comment by nfranczak** [comment]
@ethanlook yep, I believe so

https://www.npmjs.com/package/@viamrobotics/sdk/v/0.10.2-next.0?activeTab=versions

is this a mis-nomer / should be fixed?

**Comment by nfranczak** [comment]
I bumped them at 9:08 pm last night and I used `make bump-next-version`

**Comment by ethanlook** [comment]
Hmm, interesting, I feel like this could be quite confusing. Maybe we should bump an `0.11.0` version for clarity?

**Comment by nfranczak** [comment]
> Hmm, interesting, I feel like this could be quite confusing. Maybe we should bump an 0.11.0 version for clarity?

ah ok, that sounds good to me.
I want to clarify though. When you say `bump an 0.11.0 version` do you mean first bump within the typescript repo and then back here in the RDK?

If I should bump within the TS repo again. I do not think `make bump-next-version` will work though. 

Since the chronology of current versions are: `0.11.0-rc.0, 0.10.2-next.0` should next version within TS repo, if necessary, become `0.11.0-rc.1`?

**Comment by njooma** [comment]
What's the timeline on this? We cut releases branches on Thursdays, and this seems to have just missed the deadline. Normally, this would have to either wait for the next release or add this in as a hotfix.

**Comment by nfranczak** [comment]
> What's the timeline on this?

no rush. What do you recommend? @njooma

**Comment by njooma** [comment]
I think we should just let this wait and go through the normal release process then. That would mean closing this PR

**Pull request closed without merging**
