### PR TITLE
[RSDK-9028][RSDK-9026]: bme280 and sensirion sensor module

### PR DESCRIPTION
**Pull request by martha-johnston**
this pr removes the bme280 and sht3xd sensors from rdk builtins, replaced by the modules. modules pass all build tests and successfully run on hardware with the supported architectures 
[bosch module](https://github.com/viam-modules/bosch) 
[sensirion module](https://github.com/viam-modules/sensirion) 
[bosch registry](https://app.viam.com/module/viam/bosch)
[sensirion registry](https://app.viam.com/module/viam/sensirion)

### CODE REVIEW

**Review by randhid — CHANGES_REQUESTED** [review]
I like that you've linked the modules. Let's also be very detail oriented in this project and do the following:

- For each pr, link the repos you're replacing the builtins with.
- Also link the link to the module in the registry so we can check the meta json version and builds.
- Make sure that the readme is written and a good standard in the repo. My favourites are https://github.com/viam-modules/viam-camera-oak and https://github.com/viam-modules/failover. Use the template for modules that are provided in docs, you will need to edit the writing on the docs page to remove irrelevant parts for modules. 
- Add whether the module passes validation, and expected build errors if not tested with hardware, or ok if tested with hardware.
- Make a docs ticket for follow-up docs work, or link a pr if you're removing the relevant docs page yourself.

**Comment by randhid** [comment]
For this pr, please add good readmes to your modules before I approve it.

**Comment by martha-johnston** [comment]
Added a second module to this pr to avoid merge conflicts. Will update that one fully. We previously discussed copying the docs page to the module readme, so I’ll update all the readmes with your new feedback about following a module template. As for the docs page we also discussed removing them all at once, so that’s still the plan as far as I know. The existing doc ticket in the epic reflects that.

I’ll add links to the registry and that it passes. But just fyi my workflow has been to test and once everything works on the module side, remove the builtin from rdk. But yeah I’ll add a note about it since reviewers don’t know that.

**Comment by randhid** [comment]
> Added a second module to this pr to avoid merge conflicts. Will update that one fully. We previously discussed copying the docs page to the module readme, so I’ll update all the readmes with your new feedback about following a module template. As for the docs page we also discussed removing them all at once, so that’s still the plan as far as I know. The existing doc ticket in the epic reflects that.

Yes, but re: copying - we also discussed formatting the readme in a way that makes sense for module, the "test" section from the docs page does not add anything to the readme and is not something that makes sense want in the official module readmes.

Okay to remove all at once, good to know that's still the plan. Call that out in each pr. Some links in docs tutorials will be broken, just keep an eye out for that since that adds debt onto another team.

> I’ll add links to the registry and that it passes. But just fyi my workflow has been to test and once everything works on the module side, remove the builtin from rdk. But yeah I’ll add a note about it since reviewers don’t know that.

Yes, but it's always good to be transparent about what you checked so that reviewers can double check and call out things that might have been missed. With your edited comment now, I know we have a ready module.

**Comment by martha-johnston** [comment]
> > Added a second module to this pr to avoid merge conflicts. Will update that one fully. We previously discussed copying the docs page to the module readme, so I’ll update all the readmes with your new feedback about following a module template. As for the docs page we also discussed removing them all at once, so that’s still the plan as far as I know. The existing doc ticket in the epic reflects that.
> 
> Yes, but re: copying - we also discussed formatting the readme in a way that makes sense for module, the "test" section from the docs page does not add anything to the readme and is not something that makes sense want in the official module readmes.

I edited it to what I thought made sense for a module, but I missed the module README template, which is great! so just changed the two READMEs to follow that pattern. 

> Okay to remove all at once, good to know that's still the plan. Call that out in each pr. Some links in docs tutorials will be broken, just keep an eye out for that since that adds debt onto another team.

I am planning to work closely with docs on this since it is a lot, if not make the changes myself.

> > I’ll add links to the registry and that it passes. But just fyi my workflow has been to test and once everything works on the module side, remove the builtin from rdk. But yeah I’ll add a note about it since reviewers don’t know that.
> 
> Yes, but it's always good to be transparent about what you checked so that reviewers can double check and call out things that might have been missed. With your edited comment now, I know we have a ready module.

added! I'll copy and paste this format to every PR for modules

**Review by randhid — COMMENTED** [review]
Bosch has the sensiron's module name in the readme currently.

**Comment by martha-johnston** [comment]
fixed

**Review by randhid — APPROVED** [review]
Approving, but please don't merge until you have a clear path forward for migrating these.

**Comment by martha-johnston** [comment]
not planning to merge until the script you were working on is done. unless that is paused for some reason and I should write my own?

**Comment by randhid** [comment]
> not planning to merge until the script you were working on is done. unless that is paused for some reason and I should write my own?

Nope not paused, just waiting fro reviewers to review it.

**Pull request merged**
