### PR TITLE
move unused types

### PR DESCRIPTION
**Pull request by natalieh235**
move pwmChipData and noBoardError back into linux only file

### CODE REVIEW

**Review by penguinland — APPROVED** [review]
LGTM. @benjirewis, does this look right to you?

**Review by benjirewis — COMMENTED** [review]
So this wasn't failing lint in CI because CI is linux and `noBoardError` and `pwmChipData` are used in linux-only files? And, it fails on my mac because `noBoardError` and `pwmChipData` were not build-tagged with linux-only but their usages were?

**Comment by penguinland** [comment]
Exactly. They're used in files with Linux-only build tags, and Github's CI checks run on Linux, so everything looked fine. The only problem is when you try running on a Mac. So, this PR moves those parts back into the file with the Linux-only tag, and then the Macs won't see the structs at all, to go with them not seeing where the structs are used.

**Review by benjirewis — APPROVED** [review]
nice! passes `make lint` on my mac.

**Comment by penguinland** [comment]
If only the CI tests ran in a reasonable amount of time. :confounded:

**Pull request merged**
