### PR TITLE
Fix inputs in motor card

### PR DESCRIPTION
**Pull request by micheal-parks**

### CODE REVIEW

**Comment by DTCurrie** [comment]
@dannenberg were there any other component cards with the same issue?

**Comment by dannenberg** [comment]
i believe this affects all numeric fields. i personally witnessed it on board and base.

**Comment by micheal-parks** [comment]
@dannenberg Got it! Can check out those as well.

**Comment by micheal-parks** [comment]
These have been fixed in another PR. Closing and will create follow up for base and board.

**Pull request closed without merging**
