### PR TITLE
RSDK-8574: Use auto tuned control loop values without user copy/pasting in sensor controlled base

### PR DESCRIPTION
**Pull request by martha-johnston**
current issue I'm having is that the components always rebuild so I'm not sure how to maintain these values over a reconfiguration

### CODE REVIEW

**Comment by JohnN193** [comment]
> maintain these values over a reconfiguration

okay yeah setting up the gpio motor to have Reconfigure seems like it would be pretty rough. I think each model(basic/encoded/controlled) would need to setup their own reconfigure functions, and they would each first have to do all of the logic in `createNewMotor` to figure out if they have to switch motor models. 

not sure if you saw [this convo](https://viaminc.slack.com/archives/C01Q5S8V6TB/p1721333168876429), but I see like 5 possible options for this. only the 5th is "trivial"

1. figure out how to add reconfigure to the current setup
2. modularize the motor(so we can use the `VIAM_MODULE_DATA`)
3. see if we can have a dedicated folder/location to store data for builtins(i.e. VIAM_MODULE_DATA for not modules)
4. split out the motor models to be actual separate models(i wish but probably not)
5. wait until we have the "embedded storage thing" and only add the current feature to the sensorcontrolled base

**Comment by martha-johnston** [comment]
> okay yeah setting up the gpio motor to have Reconfigure seems like it would be pretty rough. 

Yeah I super don’t want to do this if we can avoid it.

I think if option 5 is something that we know will be implemented eventually we should just wait for that. But I think as it currently stands, the behavior in this PR is worse than the old behavior. Because if you go to reconfigure another component the controlled components will re-tune which could be problematic. In my opinion it’s safer to have the behavior that requires you to copy over the pid values than this which could  retune so easily. 

cc @biotinker

**Comment by biotinker** [comment]
I would agree that this is worse than current behavior; re-tuning in the middle of a run is very not desirable.

IMO the "correct" way to do this is @JohnN193's option 1, implementing `Reconfigure()` for the motors. Could you elaborate on the problems with that? I see how there are three motor types nested under GPIO that would all need `Reconfigure()` written, but they would all mostly call the same already-existing function, right?

**Comment by martha-johnston** [comment]
Could you elaborate on the problems with that? I see how there are three motor types nested under GPIO that would all need `Reconfigure()` written, but they would all mostly call the same already-existing function, right?

I've tried implementing before, and it ended up being way more complicated than we expected. there's currently 3 gpio motor types all with their own setup functions, but they all also rely on the most basic motor interface. I found it difficult because you basically have to reconfigure 2 motors every time and it was hard to figure out what exactly needed to be reconfigured. I don't 100% remember all the details of what made it complicated, I can try and look back through it and be more specific, I just remember that last time we tried to implement reconfigure we actively decided not to do it after attempting it.

**Comment by JohnN193** [comment]
yeah the issue I was having when looking at reconfigure logic was not knowing how to switch between the different motor models.

like if i wanted to go from controlled -> encoded motor, i would need the controlled motors reconfigure to have the logic to change the implementation

**Comment by martha-johnston** [comment]
yes thank you that was the biggest thing. the same type of motor card can be reconfigured to be any one of the three motors and it's hard to be aware of that in the code

**Comment by biotinker** [comment]
That makes sense.

Sounds like really, the calibration API is what should exist here.

Correct me if I'm wrong, but currently, if someone adds control params to an existing motor, it *will* auto-tune in the middle of wherever it is, right?

How does RDK currently handle reconfiguring a same-name component that is suddenly trying to be a different type, for models which do not have sub-types?

**Comment by JohnN193** [comment]
> Correct me if I'm wrong, but currently, if someone adds control params to an existing motor, it will auto-tune in the middle of wherever it is, right?

because we use always rebuild logic, if you add empty/0 pid values to a motor mid run(say after SetVelocity on a base was called) the following will happen

1. a config change occurred, stop/close the motor
2. detect pid got set, so build the motor as a controlled motor
3. notice that the pid needs to be tuned, so immediately run the tuning code
4. stop moving when pid tuning completes

all while the other motor is still moving at whatever rpm SetVelocity wanted. Worth noting even if we had reconfigure logic I believe this would still happen

**Comment by martha-johnston** [comment]
> I don't know of any other ways that people have handled this in viam outside of always rebuild

I agree I think this is why we use always rebuild for gpio motors

**Comment by randhid** [comment]
I don't want to implement a `Reconfigure` for the motor; I do not think we should.
Let's take a bit of time to look at the code and see if there's another path to get this functionality in. I also think if it's easy to implement for sensor controller base, do that first and we'll revisit motor in another pr.

**Comment by JohnN193** [comment]
Just had a thought, what is the behavior of rdk if reconfigure throws an error? Will it try to reconfigure again or will it rebuild the resource

**Comment by randhid** [comment]
> Just had a thought, what is the behavior of rdk if reconfigure throws an error? Will it try to reconfigure again or will it rebuild the resource

Always rebuild returns an error. It's a specific error to tell the manager that it's an always rebuild function. What we need is netcode to add the `shouldReconfugire` response to the reconfigure API to add more functionality to make it more flexible.

**Comment by JohnN193** [comment]
I was asking about resources with reconfigure tho, not always rebuild

**Comment by randhid** [comment]
> I was asking about resources with reconfigure tho, not always rebuild

Always rebuild implements a sturct that returns that error in reconfigure. if not it nils it out:
```go
	isModular := manager.moduleManager.Provides(conf)
	if gNode.ResourceModel() == conf.Model {
		if isModular {
			if err := manager.moduleManager.ReconfigureResource(ctx, conf, modmanager.DepsToNames(deps)); err != nil {
				return nil, false, err
			}
			return currentRes, false, nil
		}

		gNode.SetLogLevel(conf.LogConfiguration.Level)
		err = currentRes.Reconfigure(ctx, deps, conf)
		if err == nil {
			return currentRes, false, nil
		}

		if !resource.IsMustRebuildError(err) {
			return nil, false, err
		}
	} else {
		manager.logger.CInfow(ctx, "Resource models differ so resource must be rebuilt",
			"name", resName, "old_model", gNode.ResourceModel(), "new_model", conf.Model)
	}

```

**Comment by randhid** [comment]
It's how the graph node stores an always rebuild resource.

**Comment by JohnN193** [comment]
Okay, for a theoretical resource that is **not** configured with always rebuild, what happens when reconfigure throws an error while reconfiguring

**Comment by randhid** [comment]
> Okay, for a theoretical resource that is **not** configured with always rebuild, what happens when reconfigure throws an error while reconfiguring

It's returned as a nil resource to the graph, not added, and an error occurs that causes the complete config parent to exit for that node.

**Comment by randhid** [comment]
> > Okay, for a theoretical resource that is **not** configured with always rebuild, what happens when reconfigure throws an error while reconfiguring
> 
> It's returned as a nil resource to the graph, not added, and an error occurs that causes the complete config parent to exit for that node.

resource_manager is complex but from reading it that's what I understand. I think there's a way forward from within the driver but I'd like to talk about it in person with the both of you when Martha is back.

**Comment by martha-johnston** [comment]
> resource_manager is complex but from reading it that's what I understand. I think there's a way forward from within the driver but I'd like to talk about it in person with the both of you when Martha is back.

in the meantime, sensor controlled base has reconfigure already, so I should be able to fairly easily add this functionality there

**Comment by martha-johnston** [comment]
Closing because this ticket is currently blocked. Opening a new PR for RSDK-8574

**Comment by martha-johnston** [comment]
Closing because this ticket is currently blocked. Opening a new PR for RSDK-8574

**Pull request closed without merging**
