### PR TITLE
[Data-389] create schemas for camera transforms

### PR DESCRIPTION
**Pull request by bhaney**
This creates a public map in RDK of all of our transform types, with their JSON schema as values. Can be accessed in viamrobotics/app in order to populate the transform fields for the transform camera model.

### CODE REVIEW

**Comment by bhaney** [comment]
@nataliajacobowitz  FYI

**Comment by bhaney** [comment]
@maximpertsov I heard that you have some experience of populating the App fields from information found in RDK. is there anything else I need to do in order for App people to get the relevant info they need?

**Comment by maximpertsov** [comment]
> @maximpertsov I heard that you have some experience of populating the App fields from information found in RDK. is there anything else I need to do in order for App people to get the relevant info they need?

are these structs/fields part of a component config? if so, we typically just have to add them to the config struct and register via `config.RegisterComponentAttributeMapConverter`.

**Comment by bhaney** [comment]
> > @maximpertsov I heard that you have some experience of populating the App fields from information found in RDK. is there anything else I need to do in order for App people to get the relevant info they need?
> 
> 
> 
> are these structs/fields part of a component config? if so, we typically just have to add them to the config struct and register via `config.RegisterComponentAttributeMapConverter`.

These are not component configs- they are configs for individual transforms that live within the transform camera model component. The transform model already has its config registered in RegisterComponentAttributeMapConverter, but these are sub-attributes that go within its "pipeline" field. 

Even though they are not component configs, would it be useful to register them as ones anyway?

**Comment by bhaney** [comment]
@edaniels could the RegisterComponentAttributes function be expanded in a way to register configs that of things that arent technically components?

**Comment by maximpertsov** [comment]
> > > @maximpertsov I heard that you have some experience of populating the App fields from information found in RDK. is there anything else I need to do in order for App people to get the relevant info they need?
> > 
> > 
> > are these structs/fields part of a component config? if so, we typically just have to add them to the config struct and register via `config.RegisterComponentAttributeMapConverter`.
> 
> These are not component configs- they are configs for individual transforms that live within the transform camera model component. The transform model already has its config registered in RegisterComponentAttributeMapConverter, but these are sub-attributes that go within its "pipeline" field.
> 
> Even though they are not component configs, would it be useful to register them as ones anyway?

Ah got it, so generally speaking this a new kind of attribute that we're planning to expose app-side. Making the registered transforms public is enough. 

Also, we actually don't need to `jsonschema.Reflect` here - that should happen on the app side: https://github.com/viamrobotics/app/blob/main/page/robot.go#L166.

**Comment by micheal-parks** [comment]
This is the current situation:
Screen Shot 2022-10-13 at 12 07 10

It would be desirable to have something like:
```json
// Within the transform schema...
{
  "pipeline": [
    {
      "type": "identity"
    },
    {
      "type": "resize"
      "width": "number"
      "height": "number"
    },
    ...
  ]
```
Which would basically describe a one-of relationship.

**Comment by bhaney** [comment]
I think what I'll do is change to do something similar as we do for Orientation representations?

But it seems like we hard-code the allowed Orientation representation (orientation vector and quaternion) rather than getting the info of the fields from RDK

https://github.com/viamrobotics/rdk/blob/main/spatialmath/orientation_json.go#L22
https://github.com/viamrobotics/app/blob/404f0e7d9bf480782e91285eafc04d33c072c6a3/frontend/src/components/tabs/robot-components/cards/sections/frame.vue#L28

**Comment by bhaney** [comment]
> This is the current situation: Screen Shot 2022-10-13 at 12 07 10
> 
> It would be desirable to have something like:
> 
> ```json
> // Within the transform schema...
> {
>   "pipeline": [
>     {
>       "type": "identity"
>     },
>     {
>       "type": "resize"
>       "width": "number"
>       "height": "number"
>     },
>     ...
>   ]
> ```
> 
> Which would basically describe a one-of relationship.

This seems like logic that should live in viamrobotics/app, so changes to make that should happen there (and I could make a second PR in that repo). But I think all the repo that RDK provides is now public and available from this PR. 

@maximpertsov  @micheal-parks Is there anything else you need from this PR?

**Comment by bhaney** [comment]
> 



> This is the current situation: Screen Shot 2022-10-13 at 12 07 10
> 
> It would be desirable to have something like:
> 
> ```json
> // Within the transform schema...
> {
>   "pipeline": [
>     {
>       "type": "identity"
>     },
>     {
>       "type": "resize"
>       "width": "number"
>       "height": "number"
>     },
>     ...
>   ]
> ```
> 
> Which would basically describe a one-of relationship.

Actually, I think I will need to import jsonschema in RDK if I want to actually store the one-of transforms within the `RegisterComponentAttributeMapConverter` for transforms.

**Comment by bhaney** [comment]
OK! I think I finally got the JSON schema to print everything in the transform components - testing it out, it prints out the schema like 
```
            "Transformation": {
              "oneOf": [
                {
                  "$schema": "https://json-schema.org/draft/2020-12/schema",
                  "$id": "https://go.viam.com/rdk/components/camera/transformpipeline/empty-attrs",
                  "$ref": "#/$defs/emptyAttrs",
                  "$defs": {
                    "emptyAttrs": {
                      "properties": {},
                      "additionalProperties": false,
                      "type": "object"
                    }
                  },
                  "type": "depth_to_pretty"
                },
                {
                  "$schema": "https://json-schema.org/draft/2020-12/schema",
                  "$id": "https://go.viam.com/rdk/components/camera/transformpipeline/overlay-attrs",
                  "$ref": "#/$defs/overlayAttrs",
                  "type": "overlay",
                  "$defs": {
                    "PinholeCameraIntrinsics": {
                      "properties": {
                        "width_px": {
                          "type": "integer"
                        },
                        "height_px": {
                          "type": "integer"
                        },
                        "fx": {
                          "type": "number"
                        },
                        "fy": {
                          "type": "number"
                        },
                        "ppx": {
                          "type": "number"
                        },
                        "ppy": {
                          "type": "number"
                        }
                      }....
```

**Comment by maximpertsov** [comment]
removing myself from this PR since it's blocked on us upgrading our jsonschema library - feel free to add me back once that's ready

**Comment by DTCurrie** [comment]
I believe the `jsonschema` version in `app` has been bumped to be able to support this if you want to do some more in-depth testing.

**Review by DTCurrie — APPROVED** [review]
✅ LGTM. Any further work in `app` I think we can discuss in the sync up Natalia scheduled.

**Pull request merged**
