### PR TITLE
GPIO Motor refactor Remove RpmMonitorCalls

### PR DESCRIPTION
**Pull request by randhid**

### CODE REVIEW

**Review by martha-johnston — COMMENTED** [review]
will approve after quickly testing the real.setPower behavior

**Comment by martha-johnston** [comment]
`m.real.SetPower` is causing weird behavior. backwards doesn't work and motor randomly speeds up and runs indefinitely

**Comment by randhid** [comment]
> `m.real.SetPower` is causing weird behavior. backwards doesn't work and motor randomly speeds up and runs indefinitely

Okay will revert this.

**Comment by randhid** [comment]
> > `m.real.SetPower` is causing weird behavior. backwards doesn't work and motor randomly speeds up and runs indefinitely
> 
> Okay will revert this.

It might be the locks around `setPower` that eventually calls `m.real.SetPower`, but i think that means calling the underlying function might need a mutex here as well, but I'll wait until the code is less of a mess before locking state anywhere else.

**Review by martha-johnston — APPROVED** [review]

**Pull request merged**
