### PR TITLE
[RSDK-5251] Get the analog readers on all boards to configure their SPI buses themselves

### PR DESCRIPTION
**Pull request by penguinland**
Tried on both a raspberry pi and a jetson orin: works on both!

Here's an example of the old config for a board:
```
{
    "model": "pi",
    "name": "main_board",
    "namespace": "rdk",
    "type": "board",
    "attributes": {
        "spis": [
            {
            "bus_select": "0",
            "name": "main_spi_bus"
            }
        ],
        "analogs": [
            {
            "name": "reader",
            "pin": "0",
            "spi_bus": "main_spi_bus",
            "chip_select": "24",
            "average_over_ms": 100,
            "samples_per_sec": 20
            }
        ]
    }
}
```
and here's an example of the new version:
```
{
    "model": "pi",
    "name": "main_board",
    "namespace": "rdk",
    "type": "board",
    "attributes": {
        "spis": [],
        "analogs": [
            {
            "name": "reader",
            "pin": "0",
            "spi_bus": "0",
            "chip_select": "24",
            "average_over_ms": 100,
            "samples_per_sec": 20
            }
        ]
    }
}
```
This shouldn't be merged until we've got a way to migrate the configs for all the boards out there; that's the hard part of this change.

### CODE REVIEW

**Review by randhid — CHANGES_REQUESTED** [review]
Is the `MCP3008Config` used by other boards? Can we move the config to the boards that use these config parameters? 

I am particularly worried about whether the config keys exist as a standard for all boards within our board package, and I would like to attain quick wins in cleaning that code up and re-routing those attribute structs to the boards that actually us or need them. Say I have a board with direct analog readers and writers, and I register viam's `board.Config` (or whatever it's actual name is), then I have attributes that I have no use for in my configuration attributes.

**Comment by penguinland** [comment]
Although the `MCP3008AnalogConfig` and `MCP3008AnalogReader` structs are defined up in rdk/components/board/, they are only used in the pi/ and genericlinux/ subdirectories therein. (Recall that almost all boards are "subclasses" of genericlinux, so they're all covered by this change.) If you want to create a new board that has built-in analog readers, you have a choice: you can build things from scratch (so your config has only the parts you want and all is well, but you can't trivially use the pre-existing genericlinux code), or you can try to modify the genericlinux code to fit the new model. In the long run my hope is that the second option will get figured out eventually, but I think it's outside the current scope.

**Comment by randhid** [comment]
> Although the `MCP3008AnalogConfig` and `MCP3008AnalogReader` structs are defined up in rdk/components/board/, they are only used in the pi/ and genericlinux/ subdirectories therein. (Recall that almost all boards are "subclasses" of genericlinux, so they're all covered by this change.) If you want to create a new board that has built-in analog readers, you have a choice: you can build things from scratch (so your config has only the parts you want and all is well, but you can't trivially use the pre-existing genericlinux code), or you can try to modify the genericlinux code to fit the new model. In the long run my hope is that the second option will get figured out eventually, but I think it's outside the current scope.

I do think the cleanest thing to do right now, then, is to make the mcp3008 struct unexported in the raspberry pi code and in genericlinux then, which is a win for our board interface clean-up, and I would like to see that happen.

**Comment by penguinland** [comment]
Take another look. Is this what you had in mind?

**Review by randhid — APPROVED** [review]
Precisely. DO you like the package name? If so LGTM!

**Pull request merged**
