### PR TITLE
RSDK-420 add default timeout on client resources call

### PR DESCRIPTION
**Pull request by cheukt**
if we lose connection in the middle of a status refresh, we never return because of the lack of a timeout.
this causes the reconnection logic to hang (the status refresh holds a lock and we never give it up)

cc @Fahmina

### CODE REVIEW

**Review by edaniels — APPROVED** [review]
LGTM. Good catch. Why isn't it the case though that the resources call fails due to a broken pipe?

**Comment by edaniels** [comment]
Or is this refactor because status calls resources?

**Review by stuqdog — APPROVED** [review]
lgtm

**Comment by cheukt** [comment]
> LGTM. Good catch. Why isn't it the case though that the resources call fails due to a broken pipe?

not exactly sure either. might look a bit more before merging in

**Pull request merged**
